{% set name = "omicverse" %}
{% set version = "1.4.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f198100d245754cedc626ac16e7cd785bf1731979aae11a716c08150154d4cae

build:
  noarch: python
  number: 0

requirements:
  host:
    - flit >=3.2,<4
    - python >=3.8,<=3.9
    - pip
    
  run:
    - python >=3.8
    - numpy ==1.23.5
    - pandas ==1.5.3
    - matplotlib-base <3.7
    - scikit-learn >=1.2
    - scipy >=1.8
    - pytorch >=1.8
    - seaborn >=0.11
    - scanpy >=1.8
    - pybedtools >=0.8
    - gseapy ==0.10.8
    - networkx >=2.8
    - tqdm >=4.64
    - adjusttext >=0.7
    - pydeseq2 >=0.3
    - lifelines >=0.27
    - s_gd2 >=1.8
    - hnswlib >=0.7
    - multiprocess >=0.70
    - gdown >=4.6
    - igraph >=0.10
    - datashader >=0.14
    - phate >=1.0
    - wget >=3.2
    - tqdm >=4.64
    - boltons >=23.0
    
test:
  imports:
    - omicverse

about:
  home: https://github.com/Starlitnightly/omicverse
  license: GPL3
  license_family: GPL
  summary: 'A python library for multi omics included bulk and single cell RNA-seq analysis.'
  dev_url: https://github.com/Starlitnightly/omicverse

extra:
  recipe-maintainers:
    - Starlitnightly
    
