{% set name = "omicverse" %}
{% set version = "1.4.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 34f73b376bb6ea9954c7fb59237ac8423c9c89d83930d958d3ca10a88111dfc3

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - flit >=3.2,<4
    - python >=3.8
    - pip
    
  run:
    - python >=3.8
    - numpy ==1.23.5
    - pandas ==1.5.3
    - matplotlib-base <3.7
    - scikit-learn >=1.2
    - scipy >=1.8
    - pytorch >=1.8
    
test:
  imports:
    - omicverse

about:
  license: GPL3
  license_family: GPL3
  summary: 'A python library for multi omics included bulk and single cell RNA-seq analysis.'
  home: https://github.com/Starlitnightly/omicverse/
  dev_url: https://github.com/Starlitnightly/omicverse/

extra:
  recipe-maintainers:
    - Zehua Zeng <starlitnightly@163.com>
    
